urls.py
from django.urls import path, include
from . import views
from . import drf_views

from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r"usernote", drf_views.UserNoteViewSet, basename='usernote')
router.register(r"textnote", drf_views.TextNoteViewSet)
router.register(r"file", drf_views.AnyFileViewSet, basename='file')
router.register(r"users", drf_views.UserViewSet, basename='user')

app_name = "catalog"

urlpatterns = [
    path('rest/', include(router.urls), name=app_name),

    path('', views.index, name='home_page'),

    path("account/login/", views.login, name="login"),
    path("account/registration/", views.registration, name="registration"),
    path("account/logout/", views.logout_user, name="logout"),

    path("id<int:user_id>/home/", views.user_home_page, name='user_home_page'),
    path("id<int:user_id>/note/add/", views.add_user_content, name='add_user_content'),
    path("id<int:user_id>/note/<int:note_id>/view/", views.user_note_detail, name="user_note_detail"),

    path("id<int:user_id>/note/<int:note_id>/add_file/", views.add_file_for_note, name='add_file_for_note'),
    path("id<int:user_id>/note/<int:note_id>/add_text/", views.add_text_for_note, name='add_text_for_note'),

    path("id<int:user_id>/download/<int:file_id>/", views.download_user_file, name='download_user_file'),
    path("id<int:user_id>/note/<int:note_id>/file/<int:text_id>/view", views.show_user_text, name='show_user_text'),

    path("id<int:user_id>/note/<int:note_id>/file/<int:file_id>/delete/", views.delete_file_from_note, name='delete_file_from_note'),
    path("id<int:user_id>/note/<int:note_id>/delete/", views.delete_user_note, name='delete_user_note'),
    path("id<int:user_id>/note/<int:note_id>/text/<int:text_id>/delete/", views.delete_text_from_note, name='delete_text_from_note'),

    path("id<int:user_id>/note/<int:note_id>/text/<int:text_id>/edit/", views.edit_text_from_note, name='edit_text_from_note'),
    path("id<int:user_id>/note/<int:note_id>/file/<int:file_id>/edit/", views.edit_file_from_note, name='edit_file_from_note'),

    #path("test/", views.test_, name="test"),
]

models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class UserNote(models.Model):
    note_title = models.CharField(max_length=100)
    note_description = models.CharField(max_length=300, blank=True, default="")
    pub_date = models.DateTimeField("upload date", default=timezone.now)

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.note_title


class AnyFile(models.Model):
    title = models.CharField(max_length=25)
    file = models.FileField(upload_to="catalog/any_files/")
    pub_date = models.DateTimeField("upload date", default=timezone.now)

    user_note = models.ForeignKey(UserNote, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.title


class TextNote(models.Model):
    txt_title = models.CharField(max_length=25, default="", null=True)
    txt_text = models.CharField(max_length=250)
    pub_date = models.DateTimeField("upload date", default=timezone.now)

    user_note = models.ForeignKey(UserNote, on_delete=models.CASCADE)

    def __str__(self):
        return self.txt_title

templates/user/home_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Catalog Home</title>
</head>
<body>
    User: {{ user.username }}

    <div class="logout_button">
        <form action="{% url 'catalog:logout' %}" method="get">
            <button>Logout</button>
        </form>
    </div>

    {% if message %}
    <div class="message">
        <h3>{{ message }}</h3>
    </div>
    {% endif %}

    <div class="upload_content">
        <a href="{% url 'catalog:add_user_content' user.id %}">Add new note</a>
    </div>

    <div class="user_content">
        <h4 class="user_content_title">My catalog:</h4>

        {% if user.usernote_set.all %}
        <ul>
            {% for note in user.usernote_set.all %}
                <li><a href="{% url 'catalog:user_note_detail' user.pk note.pk %}">{{ note.note_title }}</a> | {{ note.pub_date }}
                    <p> {{ note.note_description }} </p> 

                    <form action="{% url 'catalog:delete_user_note' user.id note.id %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="_method" value="delete">
                        <input type="submit" value="Delete">
                    </form>

                </li> <br>
            {% endfor %}
        </ul>

        {% else %}
        <label>Your catalog is empty</label> <br>
        <label>Let's fill it </label> <a href="{% url 'catalog:add_user_content' user.id %}">by your thoughts!</a>
        {% endif %}

    </div>
</body>
</html>

templates/user/user_note_detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Catalog note</title>
</head>

<body>

        <label class="whois">User: {{ user.username }}</label>
        <br> <button><a href="{% url 'catalog:user_home_page' user.id %}">To home</a></button>


    {% if message %}
        <div class="message">
            <h2>{{ message }}</h2>
        </div>
    {% endif %}



        <div class="note">

            <div class="note_title">
                <h3>{{ note.note_title }}</h3>
            </div>

            <div class="note_description">
                <p>{{ note.note_description }}</p>
            </div>

            <div class="add_files_button">
                <form action="{% url 'catalog:add_file_for_note' user.id note.id %}" method="get">
                    {% csrf_token %}
                    <button type="submit">Add file</button>
                </form>
            </div>

            <div class="add_files_button">
                <form action="{% url 'catalog:add_text_for_note' user.id note.id %}" method="get">
                    {% csrf_token %}
                    <button type="submit">Add text</button>
                </form>
            </div>


                <label>Files:</label>
            {% if note.anyfile_set.all %}
<!--                <button><a href="{% url 'catalog:add_file_for_note' user.pk note.pk %}">Add file</a></button>-->

                <div class="note_files">

                    {% for file in note.anyfile_set.all %}
                        <ul>
                            <li>{{ file.title }} | {{ file.pub_date }}</li>
                            <a href="{% url 'catalog:download_user_file' user.id file.id %}" >Download</a>

                            <form action="{% url 'catalog:delete_file_from_note' user.id note.id file.id %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="_method" value="delete">
                                <input type="submit" value="Delete">
                            </form>

                            <form action="{% url 'catalog:edit_file_from_note' user.id note.id file.id %}" method="get">
                                <input type="submit" value="Update">
                            </form>

                        </ul>
                    {% endfor %}

                </div>
            {% endif %}

            {% if note.textnote_set.all %}

                <div class="note_texts">

                    {% for text in note.textnote_set.all %}
                        <ul>
                            <li>{{ text.txt_title }} | {{ text.pub_date }} </li>
                        
                            <a href="{% url 'catalog:show_user_text' user.id note.id text.id %}" >Full read</a>

                            <form action="{% url 'catalog:delete_text_from_note' user.id note.id text.id %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="_method" value="delete">
                                <input type="submit" value="Delete">
                            </form>

                            <form action="{% url 'catalog:edit_text_from_note' user.id note.id text.id %}" method="get">
                                <input type="submit" value="Update">
                            </form>


                        </ul>
                    {% endfor %}

                </div>
            {% endif %}

        </div>

</body>
</html>

templates/user/user_text_full.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Catalog</title>
</head>
<body>

    <label class="whois">User: {{ user.username }}</label>
    <br> <button><a href="{% url 'catalog:user_home_page' user.id %}">To home</a></button>

    {% if message %}
        <div class="message">
            <h2>{{ message }}</h2>
        </div>
    {% endif %}

    <div class="full_text">
        <h3> Published: {{ text.pub_date }} </h3>
        <h4>{{ text.txt_title }}</h4>
        <p>{{ text.txt_text }}</p>
    </div>

</body>
</html>